using System.Text;
using System.Text.RegularExpressions;

namespace KafkaStudio.Search;

/// <summary>
/// Turns a search into a runnable KafScript check, so a question asked once by hand ("does order
/// ORD-42 exist on shipments?") can become a scenario or a scheduled Task.
///
/// KafScript conditions are AND-only, case-sensitive and support key/value/json fields with
/// equals/contains/matches/not equals; this generator translates what it can (case-insensitive and
/// starts/ends-with comparisons become anchored <c>(?i)</c> regexes) and reports clearly what it can't
/// (or/not, headers, "similar to", exists/missing...).
/// </summary>
public static class KafScriptGenerator
{
    public sealed record Options
    {
        public required string Connection { get; init; }
        public required IReadOnlyList<string> Topics { get; init; }
        public string Name { get; init; } = "Data exists";

        /// <summary>When set, generates a scheduled <c>Task</c> instead of a one-off <c>Scenario</c>.</summary>
        public string? TaskSchedule { get; init; }

        public int WithinSeconds { get; init; } = 30;
    }

    public static bool TryGenerate(MessageQuery query, Options options, out string script, out string? error)
    {
        script = "";
        if (options.Topics.Count == 0)
        {
            error = "no topics to check - run the search first or pick a topic set";
            return false;
        }

        if (!TryTranslate(query, out var conditions, out error)) return false;

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by KafkaStudio from the search: {query.Text.Replace('\n', ' ')}");
        if (!query.IsStructured && query.Options.Fields != SearchFields.Value)
        {
            sb.AppendLine("# Note: KafScript conditions check the message value; the search also looked at keys/headers.");
        }
        sb.AppendLine("# Each block passes when at least one matching message exists on (or arrives at) the topic.");

        foreach (var topic in options.Topics)
        {
            sb.AppendLine();
            var name = BlockName(options.Topics.Count == 1 ? options.Name : $"{options.Name} on {topic}");
            if (options.TaskSchedule is { } schedule)
            {
                sb.AppendLine($"Task: {name}");
                sb.AppendLine($"schedule {schedule}");
            }
            else
            {
                sb.AppendLine($"Scenario: {name}");
            }
            sb.AppendLine($"Given use connection {Str(options.Connection)}");
            sb.AppendLine($"And watch topic {Str(topic)} from beginning");
            var where = conditions.Count == 0 ? "" : " where " + string.Join(" and ", conditions);
            sb.AppendLine($"Then expect message on topic {Str(topic)} within {options.WithinSeconds} seconds{where}");
        }

        script = sb.ToString();
        error = null;
        return true;
    }

    /// <summary>KafScript condition texts for <paramref name="query"/> (e.g. <c>json "$.id" equals "42"</c>).</summary>
    public static bool TryTranslate(MessageQuery query, out List<string> conditions, out string? error)
    {
        conditions = new List<string>();
        error = null;
        var ignoreCase = !query.Options.CaseSensitive;

        if (!query.IsStructured)
        {
            var term = query.Term!;
            switch (query.Options.Mode)
            {
                case TextMatchMode.Contains:
                    conditions.Add(ignoreCase ? $"value matches {Str("(?i)" + Regex.Escape(term))}" : $"value contains {Str(term)}");
                    return true;
                case TextMatchMode.Exact:
                    conditions.Add(ignoreCase ? $"value matches {Str("(?i)^\\s*" + Regex.Escape(term) + "\\s*$")}" : $"value equals {Str(term)}");
                    return true;
                case TextMatchMode.WholeWord:
                    conditions.Add($"value matches {Str((ignoreCase ? "(?i)" : "") + @"(?<![\w-])" + Regex.Escape(term) + @"(?![\w-])")}");
                    return true;
                case TextMatchMode.Regex:
                    conditions.Add($"value matches {Str((ignoreCase ? "(?i)" : "") + term)}");
                    return true;
                default:
                    error = "fuzzy searches can't be expressed in KafScript - switch to 'contains', 'exact' or a structured query";
                    return false;
            }
        }

        var flat = new List<QueryCondition>();
        if (!Flatten(query.Root!, flat, out error)) return false;
        foreach (var c in flat)
        {
            if (!TryTranslateCondition(c, ignoreCase, out var text, out error)) return false;
            conditions.Add(text);
        }
        return true;
    }

    private static bool Flatten(QueryNode node, List<QueryCondition> into, out string? error)
    {
        error = null;
        switch (node)
        {
            case QueryAnd and:
                return Flatten(and.Left, into, out error) && Flatten(and.Right, into, out error);
            case QueryCondition condition:
                into.Add(condition);
                return true;
            case QueryOr:
                error = "KafScript conditions can only be combined with 'and' - split the 'or' into separate checks";
                return false;
            default:
                error = "KafScript has no 'not (...)' - use 'not equals' on a single field instead";
                return false;
        }
    }

    private static bool TryTranslateCondition(QueryCondition c, bool ignoreCase, out string text, out string? error)
    {
        text = "";
        error = null;
        string field;
        switch (c.Field.Kind)
        {
            case FieldKind.Key: field = "key"; break;
            case FieldKind.Value: field = "value"; break;
            case FieldKind.Json: field = $"json {Str(c.Field.Name!)}"; break;
            default:
                error = $"KafScript conditions can't check '{c.Field}' - only key, value and json \"$.path\"";
                return false;
        }

        var expected = c.Expected ?? "";
        var escaped = Regex.Escape(expected);
        var prefix = ignoreCase ? "(?i)" : "";
        switch (c.Comparator)
        {
            case QueryComparator.Equals:
                text = ignoreCase ? $"{field} matches {Str($"{prefix}^{escaped}$")}" : $"{field} equals {Str(expected)}";
                return true;
            case QueryComparator.NotEquals when !ignoreCase:
                text = $"{field} not equals {Str(expected)}";
                return true;
            case QueryComparator.Contains:
                text = ignoreCase ? $"{field} matches {Str(prefix + escaped)}" : $"{field} contains {Str(expected)}";
                return true;
            case QueryComparator.StartsWith:
                text = $"{field} matches {Str($"{prefix}^{escaped}")}";
                return true;
            case QueryComparator.EndsWith:
                text = $"{field} matches {Str($"{prefix}{escaped}$")}";
                return true;
            case QueryComparator.Matches:
                text = $"{field} matches {Str(prefix + expected)}";
                return true;
            case QueryComparator.Exists:
                text = $"{field} matches {Str("(?s).*")}";
                return true;
            default:
                error = $"'{MessageQuery.ComparatorText(c.Comparator)}'{(c.Comparator == QueryComparator.NotEquals ? " (case-insensitive)" : "")} can't be expressed as a KafScript condition";
                return false;
        }
    }

    /// <summary>
    /// Makes text safe as a Scenario/Task name: KafScript names are words, so only letters, digits,
    /// '_' and '-'/'.' inside a word survive; everything else becomes a space.
    /// </summary>
    public static string BlockName(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            var previous = sb.Length > 0 ? sb[^1] : ' ';
            if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
            else if (c is '-' or '.' && char.IsLetterOrDigit(previous)) sb.Append(c);
            else if (previous != ' ') sb.Append(' ');
        }
        var result = sb.ToString().Trim().TrimEnd('-', '.').Trim();
        return result.Length == 0 ? "Data exists" : result;
    }

    /// <summary>A KafScript string literal (backslashes and quotes escaped).</summary>
    public static string Str(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";
}
